//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mentorsoft.ro/WebPOS/", ConfigurationName="ServiceReference1.WSSoap")]
    public interface WSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mentorsoft.ro/WebPOS/getRetete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> getReteteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mentorsoft.ro/WebPOS/getVotableRetete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> getVotableReteteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mentorsoft.ro/WebPOS/setVotingProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task setVotingProductsAsync(string productList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mentorsoft.ro/WebPOS/setResetVotingProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task setResetVotingProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mentorsoft.ro/WebPOS/getVotesForRetete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> getVotesForReteteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mentorsoft.ro/WebPOS/setVoteCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task setVoteCountAsync(string productList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mentorsoft.ro/WebPOS/setResetVoteCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task setResetVoteCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mentorsoft.ro/WebPOS/getRetetar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> getRetetarAsync(string cod_produs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WSSoapChannel : ServiceReference1.WSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WSSoap>, ServiceReference1.WSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSSoapClient.GetBindingForEndpoint(endpointConfiguration), WSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> getReteteAsync()
        {
            return base.Channel.getReteteAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> getVotableReteteAsync()
        {
            return base.Channel.getVotableReteteAsync();
        }
        
        public System.Threading.Tasks.Task setVotingProductsAsync(string productList)
        {
            return base.Channel.setVotingProductsAsync(productList);
        }
        
        public System.Threading.Tasks.Task setResetVotingProductsAsync()
        {
            return base.Channel.setResetVotingProductsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> getVotesForReteteAsync()
        {
            return base.Channel.getVotesForReteteAsync();
        }
        
        public System.Threading.Tasks.Task setVoteCountAsync(string productList)
        {
            return base.Channel.setVoteCountAsync(productList);
        }
        
        public System.Threading.Tasks.Task setResetVoteCountAsync()
        {
            return base.Channel.setResetVoteCountAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> getRetetarAsync(string cod_produs)
        {
            return base.Channel.getRetetarAsync(cod_produs);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.13.13:8432/WS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.13.13:8432/WS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSSoap,
            
            WSSoap12,
        }
    }
}
